site_name: Athenian Robotics
site_url: http://www.athenian-robotics.org
site_description: Athenian Robotics Documentation
site_author: Athenian Robotics Team

pages:
- Home: index.md
- Software Notes:
  - MkDocs: mkdocs.md
  - MQTT: mqtt.md
  - Plot.ly: plotly.md

theme: readthedocs

extra_css: [extra.css]

google_analytics: ['UA-90285378-1', 'auto']

repo_url: https://github.com/athenian-robotics/athenian-robotics.github.io

