site_name: Athenian Robotics
site_url: http://www.athenian-robotics.org
site_description: Athenian Robotics Documentation
site_author: Athenian Robotics Team

pages:
- Home: index.md
- Machine Setup:
  - OSX: osx-setup.md
  - Windows: windows-setup.md
- Python:
  - Admin: python-admin.md
  - Links: python-links.md
  - REPL 1: repl1.md
- EV3:
  - Admin: ev3-admin.md
  - Python: ev3-python.md
- Software Notes:
  - Git: git.md
  - Homebrew: homebrew.md
  - MQTT: mqtt.md
  - Plot.ly: plotly.md
  - OpenCV: opencv.md
  - XQuartz: xquartz.md
  - MkDocs: mkdocs.md
- Hardware Notes:
  - Raspberry Pi: raspberrypi.md
  - Blinkt: blinkt.md
  - Unicorn Hat: unicorn.md
  - Display-O-Tron Hat: displayotron.md
  - GoPiGo: gopigo.md

theme: readthedocs

extra_css: [extra.css]

google_analytics: ['UA-90285378-1', 'auto']

repo_url: https://github.com/athenian-robotics/athenian-robotics.github.io

