site_name: Athenian Robotics
site_url: http://www.athenian-robotics.org
site_description: Athenian Robotics Documentation
site_author: Athenian Robotics Team

pages:
- Home: index.md
- Github Repos: github-repos.md
- Machine Setup:
  - OSX: osx-setup.md
  - Raspbian: raspbian.md
  - Raspberry Pi Zero W: raspipizero.md
  - Windows: windows-setup.md
- Python:
  - Admin: python-admin.md
  - Links: python-links.md
  - REPL 1: repl1.md
- Python Packages:
  - OpenCV: opencv.md
  - imutils: imutils.md
  - pyserial: pyserial.md
  - numpy: numpy.md
  - gRPC: grpc.md
  - MQTT Client: mqtt-client.md
  - pyFirmata: pyfirmata.md
  - Tkinter: tkinter.md
- Software Notes:
  - Git: git.md
  - Go: go-admin.md
  - PyCharm: pycharm.md
  - Homebrew: homebrew.md
  - MQTT Broker: mqtt-broker.md
  - Plot.ly: plotly.md
  - nginx: nginx.md
  - XQuartz: xquartz.md
  - ROS: ros.md
  - MkDocs: mkdocs.md
- Hardware Notes:
  - SD Cards: sdcards.md
  - Metro Mini: metro-mini.md
  - Blinkt: blinkt.md
  - Unicorn Hat: unicorn.md
  - Display-O-Tron Hat: displayotron.md
  - Pan-Tilt Hat: pantilthat.md
  - 9-DOF Sensor: motion-sensor.md
  - VL53L0X Time of Flight Sensor: vl53l0x.md
  - roboRIO: roborio.md
- Robots:
  - GoPiGo: gopigo.md
  - EV3:
    - Admin: ev3-admin.md
    - Python: ev3-python.md


theme: readthedocs

extra_css: [extra.css]

google_analytics: ['UA-90285378-1', 'auto']

repo_url: https://github.com/athenian-robotics/athenian-robotics.github.io

