site_name: Athenian Robotics
site_url: http://www.athenian-robotics.org
site_description: Athenian Robotics Documentation
site_author: Athenian Robotics Team

pages:
- Home: index.md
- Github Repos: github-repos.md
- Linux:
  - Raspbian: raspbian.md
  - Ubuntu: ubuntu.md
  - General Linux: linux.md
- ROS:
  - Admin: ros-admin.md
  - Commands: ros-commands.md
  - ROS Serial: ros-serial.md
- Python:
  - Admin: python-admin.md
  - Links: python-links.md
  - Packages: python-packages.md
  - Tutorials: python-tutorials.md
  - REPL 1: repl1.md
- Software:
  - Git: git.md
  - Go: go-admin.md
  - Docker: docker.md
  - PyCharm: pycharm.md
  - Homebrew: homebrew.md
  - MQTT Broker: mqtt-broker.md
  - Plot.ly: plotly.md
  - nginx: nginx.md
  - XQuartz: xquartz.md
  - APT: apt.md
  - Gazebo: gazebo.md
  - Prometheus: prometheus.md
  - AI Projects: ai-projects.md
  - Kotlin: kotlin.md
  - Grafana: grafana.md
  - MkDocs: mkdocs.md
- Hardware:
  - Nvidia Jetson TX2: jetsontx2.md
  - Logitech Joystick: joystick.md
  - SD Cards: sdcards.md
  - Arduino: arduino.md
  - Metro Mini: metro-mini.md
  - Blinkt: blinkt.md
  - Unicorn Hat: unicorn.md
  - Display-O-Tron Hat: displayotron.md
  - Pan-Tilt Hat: pantilthat.md
  - 9-DOF Sensor: motion-sensor.md
  - VL53L0X Time of Flight Sensor: vl53l0x.md
  - roboRIO: roborio.md
  - Intel Euclid: euclid.md
  - Adafruit Circuit Playground: circuitplayground.md
- Machine Setup:
  - OSX: osx-setup.md
  - Raspberry Pi Zero W: raspipizero.md
  - Windows: windows-setup.md
- Robots:
  - TurtleBot3: turtlebot3.md
  - GoPiGo: gopigo.md
  - EV3:
    - Admin: ev3-admin.md
    - Python: ev3-python.md
    - ROS: ev3-ros.md
- Education:
  - Robots: education-robots.md
  - Software: education-software.md


theme: readthedocs

extra_css: [extra.css]

google_analytics: ['UA-90285378-1', 'auto']

repo_url: https://github.com/athenian-robotics/athenian-robotics.github.io

